services:
    brctx.xrealip.listener:
        class: brctx\xrealip\event\main_listener
        arguments:
            - '@request'
            - '@cache'
        tags:
            - { name: event.listener }
